baseURL       = "https://taupins.myecl.fr/"
languageCode  = "fr-fr"
title         = "Semaine Taupin | On the WEIve"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Accueil"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Notre équipe"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Restauration"
    url     = "restauration"
    weight  = 3
  [[menu.nav]]
    name    = "Activités"
    url     = "activites"
    weight  = 4
  [[menu.nav]]
    name    = "S'orienter"
    url     = "orientation"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Semaine Taupin | On the WEIve"
  author = "ÉCLAIR"

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Le guide du taupin"
    tagline               = "École Centrale de Lyon"
    primary_button        = "Activités proposées "
    primary_button_url    = "activites"
    secondary_button      = "Plan du campus"
    secondary_button_url  = "orientation"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Bienvenue"
    title1              = "Bonjour et bienvenue pour cette semaine d’écrits du concours Centrale-Supélec sur le campus de l’Ecole Centrale de Lyon ! Tu trouveras sur ce site toutes les infos qui peuvent t’être utiles au cours de ces 4 jours intenses (nutrition, orientation, détente, contacts importants...). Après 2 (voire 3) ans intensifs, tu es dans la dernière ligne droite, alors souffle un bon coup, aie confiance en toi, et bonne chance pour tes écrits !"